### ISSUE TITLE
Compile error when building table allocator server

### ISSUE THREAD

**Issue by SPYFF** [kristrev/multihomed-routing#1]
Followed the instructions (after installed libjson-c-dev, libuv-dev, libsqlite3-dev packages) I give this error when make. Do you have any idea? Thanks!

edit: looks like its too long, but I keep it here because of the google search results. 
Also copyed here for better visuals: https://pastebin.com/Eis2Ksnk

`[ 33%] Built target table_allocator_shared
[ 41%] Building C object server/CMakeFiles/table_allocator_server.dir/src/table_allocator_server_sockets.c.o
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c: In function ‘unix_socket_handle_close_cb’:
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:42:56: warning: passing argument 2 of ‘uv_timer_start’ from incompatible pointer type [-Wincompatible-pointer-types]
     uv_timer_start(&(ctx->unix_socket_timeout_handle), unix_socket_timeout_cb,
                                                        ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/include/table_allocator_server_sockets.h:20:0,
                 from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:21:
/usr/include/uv.h:1242:15: note: expected ‘uv_timer_cb {aka void (*)(struct uv_timer_s *, int)}’ but argument is of type ‘void (*)(uv_timer_t *) {aka void (*)(struct uv_timer_s *)}’
 UV_EXTERN int uv_timer_start(uv_timer_t* handle,
               ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:25:0:
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c: In function ‘unix_socket_recv_cb’:
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:76:29: error: incompatible type for argument 1 of ‘uv_strerror’
                 uv_strerror(nread));
                             ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/shared/include/table_allocator_shared_log.h:25:76: note: in definition of macro ‘TA_SYSLOG’
 #define TA_SYSLOG(priority, ...){syslog(LOG_MAKEPRI(LOG_DAEMON, priority), __VA_ARGS__);}
                                                                            ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:75:9: note: in expansion of macro ‘TA_PRINT_SYSLOG’
         TA_PRINT_SYSLOG(ctx, LOG_DEBUG, "Server socket failed, error: %s\n",
         ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/include/table_allocator_server_sockets.h:20:0,
                 from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:21:
/usr/include/uv.h:450:23: note: expected ‘uv_err_t {aka struct uv_err_s}’ but argument is of type ‘ssize_t {aka long int}’
 UV_EXTERN const char* uv_strerror(uv_err_t err);
                       ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:25:0:
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:76:29: error: incompatible type for argument 1 of ‘uv_strerror’
                 uv_strerror(nread));
                             ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/shared/include/table_allocator_shared_log.h:24:40: note: in definition of macro ‘TA_PRINT2’
 #define TA_PRINT2(fd, ...){fprintf(fd, __VA_ARGS__);fflush(fd);}
                                        ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:75:9: note: in expansion of macro ‘TA_PRINT_SYSLOG’
         TA_PRINT_SYSLOG(ctx, LOG_DEBUG, "Server socket failed, error: %s\n",
         ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/include/table_allocator_server_sockets.h:20:0,
                 from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:21:
/usr/include/uv.h:450:23: note: expected ‘uv_err_t {aka struct uv_err_s}’ but argument is of type ‘ssize_t {aka long int}’
 UV_EXTERN const char* uv_strerror(uv_err_t err);
                       ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:122:5: warning: implicit declaration of function ‘uv_fileno’ [-Wimplicit-function-declaration]
     uv_fileno((const uv_handle_t*) handle, &sock_fd);
     ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:25:0:
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:129:71: error: ‘errno’ undeclared (first use in this function)
         TA_PRINT_SYSLOG(ctx, LOG_ERR, "Sending error: %s\n", strerror(errno));
                                                                       ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/shared/include/table_allocator_shared_log.h:25:76: note: in definition of macro ‘TA_SYSLOG’
 #define TA_SYSLOG(priority, ...){syslog(LOG_MAKEPRI(LOG_DAEMON, priority), __VA_ARGS__);}
                                                                            ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:129:9: note: in expansion of macro ‘TA_PRINT_SYSLOG’
         TA_PRINT_SYSLOG(ctx, LOG_ERR, "Sending error: %s\n", strerror(errno));
         ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:129:71: note: each undeclared identifier is reported only once for each function it appears in
         TA_PRINT_SYSLOG(ctx, LOG_ERR, "Sending error: %s\n", strerror(errno));
                                                                       ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/shared/include/table_allocator_shared_log.h:25:76: note: in definition of macro ‘TA_SYSLOG’
 #define TA_SYSLOG(priority, ...){syslog(LOG_MAKEPRI(LOG_DAEMON, priority), __VA_ARGS__);}
                                                                            ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:129:9: note: in expansion of macro ‘TA_PRINT_SYSLOG’
         TA_PRINT_SYSLOG(ctx, LOG_ERR, "Sending error: %s\n", strerror(errno));
         ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c: In function ‘unix_socket_timeout_cb’:
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:151:42: error: ‘errno’ undeclared (first use in this function)
                         "%s\n", strerror(errno));
                                          ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/shared/include/table_allocator_shared_log.h:25:76: note: in definition of macro ‘TA_SYSLOG’
 #define TA_SYSLOG(priority, ...){syslog(LOG_MAKEPRI(LOG_DAEMON, priority), __VA_ARGS__);}
                                                                            ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:150:17: note: in expansion of macro ‘TA_PRINT_SYSLOG’
                 TA_PRINT_SYSLOG(ctx, LOG_ERR, "Failed to create domain socket: "
                 ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:163:17: warning: passing argument 2 of ‘uv_udp_recv_start’ from incompatible pointer type [-Wincompatible-pointer-types]
                 unix_socket_alloc_cb, unix_socket_recv_cb);
                 ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/include/table_allocator_server_sockets.h:20:0,
                 from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:21:
/usr/include/uv.h:973:15: note: expected ‘uv_alloc_cb {aka struct <anonymous> (*)(struct uv_handle_s *, long unsigned int)}’ but argument is of type ‘void (*)(uv_handle_t *, size_t,  uv_buf_t *) {aka void (*)(struct uv_handle_s *, long unsigned int,  struct <anonymous> *)}’
 UV_EXTERN int uv_udp_recv_start(uv_udp_t* handle, uv_alloc_cb alloc_cb,
               ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:163:39: warning: passing argument 3 of ‘uv_udp_recv_start’ from incompatible pointer type [-Wincompatible-pointer-types]
                 unix_socket_alloc_cb, unix_socket_recv_cb);
                                       ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/include/table_allocator_server_sockets.h:20:0,
                 from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:21:
/usr/include/uv.h:973:15: note: expected ‘uv_udp_recv_cb {aka void (*)(struct uv_udp_s *, long int,  struct <anonymous>,  struct sockaddr *, unsigned int)}’ but argument is of type ‘void (*)(uv_udp_t *, ssize_t,  const uv_buf_t *, const struct sockaddr *, unsigned int) {aka void (*)(struct uv_udp_s *, long int,  const struct <anonymous> *, const struct sockaddr *, unsigned int)}’
 UV_EXTERN int uv_udp_recv_start(uv_udp_t* handle, uv_alloc_cb alloc_cb,
               ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:25:0:
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:167:49: error: incompatible type for argument 1 of ‘uv_strerror’
                             "%s\n", uv_strerror(retval));
                                                 ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/shared/include/table_allocator_shared_log.h:25:76: note: in definition of macro ‘TA_SYSLOG’
 #define TA_SYSLOG(priority, ...){syslog(LOG_MAKEPRI(LOG_DAEMON, priority), __VA_ARGS__);}
                                                                            ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:166:13: note: in expansion of macro ‘TA_PRINT_SYSLOG’
             TA_PRINT_SYSLOG(ctx, LOG_ERR, "Failed to start domain socket: "
             ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/include/table_allocator_server_sockets.h:20:0,
                 from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:21:
/usr/include/uv.h:450:23: note: expected ‘uv_err_t {aka struct uv_err_s}’ but argument is of type ‘int32_t {aka int}’
 UV_EXTERN const char* uv_strerror(uv_err_t err);
                       ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:25:0:
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:167:49: error: incompatible type for argument 1 of ‘uv_strerror’
                             "%s\n", uv_strerror(retval));
                                                 ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/shared/include/table_allocator_shared_log.h:24:40: note: in definition of macro ‘TA_PRINT2’
 #define TA_PRINT2(fd, ...){fprintf(fd, __VA_ARGS__);fflush(fd);}
                                        ^
/home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:166:13: note: in expansion of macro ‘TA_PRINT_SYSLOG’
             TA_PRINT_SYSLOG(ctx, LOG_ERR, "Failed to start domain socket: "
             ^
In file included from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/include/table_allocator_server_sockets.h:20:0,
                 from /home/mptcp/mptcp-script/multihomed-routing/table_allocator/server/src/table_allocator_server_sockets.c:21:
/usr/include/uv.h:450:23: note: expected ‘uv_err_t {aka struct uv_err_s}’ but argument is of type ‘int32_t {aka int}’
 UV_EXTERN const char* uv_strerror(uv_err_t err);
                       ^
server/CMakeFiles/table_allocator_server.dir/build.make:86: recipe for target 'server/CMakeFiles/table_allocator_server.dir/src/table_allocator_server_sockets.c.o' failed
make[2]: *** [server/CMakeFiles/table_allocator_server.dir/src/table_allocator_server_sockets.c.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'server/CMakeFiles/table_allocator_server.dir/all' failed
make[1]: *** [server/CMakeFiles/table_allocator_server.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by kristrev** [comment]
Wrt. errno, that could be a missing include, but I think we should get rid of the messages related to libuv first. It seems that your version of libuv might be too old. My version of libuv (dpkg -s libuv1) is 1.9.1-3. Have you also installed the libuv package, and not just the development files?

**Comment by SPYFF** [comment]
Thank you, that was the problem! (I only installed the development files, not the lib)

**Comment by kristrev** [comment]
Great!
